import Navigation from "@/components/Navigation";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="favicon.ico" />
        <link
          rel="stylesheet"
          href="https://bootswatch.com/5/slate/bootstrap.min.css"
        />
      </head>
      <body>
        <Navigation />
        <div className="conainer p-4"> {children} </div>
      </body>
    </html>
  );
}
